name: deploy-resources
on:
  push:
    branches:
      - master
      - stage
jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - run: curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
      - run: unzip awscli-bundle.zip
      - run: ./awscli-bundle/install -b ~/bin/aws
      - run: npm install
      - run: node deploy-resources -b ${{ steps.extract_branch.outputs.branch }}
      - name: Web deploy
        run: aws s3 cp dist/ s3://sabbath-school`[[ "${{ steps.extract_branch.outputs.branch }}" = "stage" ]] && echo '-stage'`.adventech.io --acl "public-read" --region us-east-1 --no-progress --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}