name: deploy
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

env:
  DEPLOY_ENV: ${{ inputs.branch }}

jobs:
  deploy-resources:
    if: (github.repository == 'Adventech/sabbath-school-resources')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
        name: Fetch the repository files
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '16'
      - run: npm install --global yarn
        name: Install Yarn
      - run: yarn install
        name: Installing dependencies
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$CREDS_PASSPHRASE" --output deploy-creds.tar deploy-creds.tar.gpg
        env:
          CREDS_PASSPHRASE: ${{ secrets.CREDS_PASSPHRASE }}
        working-directory: ops/deploy/creds
      - run: tar xvf deploy-creds.tar
        working-directory: ops/deploy/creds
      - run: node ops/deploy/deploy-documents.js
        name: Deploy documents
      - run: node ops/deploy/deploy-sections.js
        name: Deploy categories
      - run: node ops/deploy/deploy-categories.js
        name: Deploy categories
      - run: node ops/deploy/deploy-authors.js
        name: Deploy authors
      - run: node ops/deploy/deploy-resources.js
        name: Deploy resources
      - run: node ops/deploy/deploy-languages.js
        name: Deploy languages
      - run: aws s3 cp dist/ s3://sabbath-school`[[ "${{ inputs.branch }}" = "stage" ]] && echo '-stage'`.adventech.io --acl "public-read" --region us-east-1 --no-progress --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}