name: port-from-v2

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  port-from-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Fetch the repository files
        with:
          ref: stage
      - name: Create port dir
        run: mkdir port
      - name: Sync ported content from s3
        run: aws s3 cp s3://sabbath-school-media-tmp/port/ss-`echo '${{ github.event.client_payload.port_id }}'`/ ./port --recursive --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Running rsync
        run: rsync -a ./port/ ./src/
      - name: Remove port dir
        run: rm -r ./port
      - name: Git Add all new files
        run: git add -A
      - name: Reset yarn.lock
        run: git restore yarn.lock
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: stage
          github_token: ${{ secrets.PACKAGES_SECRET }}
